apiVersion: skaffold/v4beta1
kind: Config
deploy:
  kubectl: {}
build:
  googleCloudBuild:
    projectId: student-hub-381513
  # local:
  #   push: false
  artifacts:
    # - image: htekeste/auth
    - image: us.gcr.io/student-hub-381513/auth
      context: Auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # # - image: htekeste/client
    # # # - image: us.gcr.io/student-hub-381513/client
    # #   context: client
    # #   docker:
    # #     dockerfile: Dockerfile
    # #   sync:
    # #     manual:
    # #       - dest: .
    # #         src: "**/*.js"
    # # - image: htekeste/application
    - image: us.gcr.io/student-hub-381513/application
      context: Application
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # # - image: htekeste/blog-feed
    # - image: us.gcr.io/student-hub-381513/blog-feed
    #   context: BlogFeed
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: "src/**/*.ts"
    # # - image: htekeste/blog-post
    # - image: us.gcr.io/student-hub-381513/blog-post
    #   context: BlogPost
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: "src/**/*.ts"
    # # - image: htekeste/comment
    # - image: us.gcr.io/student-hub-381513/comment
    #   context: Comment
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: "src/**/*.ts"
    # # - image: htekeste/comment-moderation
    # - image: us.gcr.io/student-hub-381513/comment-moderation
    #   context: CommentModeration
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: "src/**/*.ts"
    # # - image: htekeste/profile
    - image: us.gcr.io/student-hub-381513/profile
      context: Profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # # - image: htekeste/project
    - image: us.gcr.io/student-hub-381513/project
      context: Project
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # - image: htekeste/project-feed
    - image: us.gcr.io/student-hub-381513/project-feed
      context: ProjectFeed
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
manifests:
  rawYaml:
    - "./infra/k8s/auth-depl.yaml"
    - "./infra/k8s/auth-mongo-depl.yaml"
    - "./infra/k8s/project-depl.yaml"
    - "./infra/k8s/project-mongo-depl.yaml"
    - "./infra/k8s/profile-depl.yaml"
    - "./infra/k8s/profile-mongo-depl.yaml"
    - "./infra/k8s/application-depl.yaml"
    - "./infra/k8s/application-mongo-depl.yaml"
    - "./infra/k8s/project-feed-depl.yaml"
    - "./infra/k8s/project-feed-mongo-depl.yaml"
    - "./infra/k8s/nats-depl.yaml"
 