apiVersion: skaffold/v4beta1
kind: Config
deploy:
  kubectl: {}
build:
  googleCloudBuild:
    projectId: student-hub-381513
  artifacts:
    - image: us.gcr.io/student-hub-381513/auth
      context: Auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # - image: us.gcr.io/student-hub-381513/client
    #   context: client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: "**/*.js"
    - image: us.gcr.io/student-hub-381513/application
      context: Application
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/student-hub-381513/blog-feed
      context: BlogFeed
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/student-hub-381513/blog-post
      context: BlogPost
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/student-hub-381513/comment
      context: Comment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/student-hub-381513/comment-moderation
      context: CommentModeration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/student-hub-381513/profile
      context: Profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/student-hub-381513/project
      context: Project
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/student-hub-381513/project-feed
      context: ProjectFeed
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
manifests:
  rawYaml:
    - "./infra/k8s/*"
 