export enum streamConfig {
  StreamName = "mystream",
  UCreatedQueueName = "user-created",
  UCreatedDurableName = "userCreated",
  CCreatedQueueName = "comment-created",
  CCreatedDurableName = "commentCreated",
  BCreatedQueueName = "qbook-created",
  BCreatedDurableName = "qbookCreated",
  RCreatedQueueName = "reply-created",
  RCreatedDurableName = "replyCreated",
  CUpdatedQueueName = "comment-updated",
  CUpdatedDurableName = "commentUpdated",
  RUpdatedQueueName = "reply-updated",
  RUpdatedDurableName = "replyUpdated",
  BUpdatedQueueName = "qbook-updated",
  BUpdatedDurableName = "qbookUpdated",
}
