apiVersion: apps/v1
kind: Deployment
metadata:
  name: answer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: answer
  template:
    metadata:
      labels:
        app: answer
    spec:
      containers:
        - name: answer
          image: us.gcr.io/student-hub-381513/answer
          # image: htekeste/answer
          env:
            - name: MONGO_URI
              value: "mongodb+srv://meksonbravo903:meksonbravo903@cluster0.oqqqvzw.mongodb.net/?retryWrites=true&w=majority/Answer"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key
                  key: JWT_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: answer-srv
spec:
  selector:
    app: answer
  ports:
    - port: 4008
      targetPort: 4008
      name: answer-port
      protocol: TCP
