apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-post-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-post
  template:
    metadata:
      labels:
        app: blog-post
    spec:
      containers:
        - name: blog-post
          image: us.gcr.io/student-hub-381513/blog-post
          # image: htekeste/blog-post
          env:
            - name: MONGO_URI
              value: "mongodb://blog-post-mongo-srv:27017/BlogPost"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key
                  key: JWT_KEY
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-cloud
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-api
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_SECRET
            - name: NATS_URL
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: blog-post-srv
spec:
  selector:
    app: blog-post
  ports:
    - port: 4006
      targetPort: 4006
      name: blog-post-port
      protocol: TCP
