apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
      - name: book
        image: us.gcr.io/student-hub-381513/book
        env:
            - name: MONGO_URI
              value: "mongodb+srv://meksonbravo903:meksonbravo903@cluster0.nby8wro.mongodb.net/Book?retryWrites=true&w=majority"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key
                  key: JWT_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: booki
            - name: CLOUDINARY_API_SECRET
              value: M9ogGdjy3bXRVem3Luzj2hq6FLM
            - name: CLOUDINARY_CLOUD_NAME
              value: doo1ivw33
            - name: CLOUDINARY_API_KEY
              value: '468296274266559'
---
apiVersion: v1
kind: Service
metadata:
  name: book-srv
spec:
  selector:
    app: book
  ports:
  - name: book
    protocol: TCP
    port: 3001
    targetPort: 3001
