apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
      - name: exchange
        image: us.gcr.io/student-hub-381513/exchange
        env:
            - name: MONGO_URI
              value: "mongodb+srv://meksonbravo903:meksonbravo903@cluster0.yhxikae.mongodb.net/Exchange?retryWrites=true&w=majority"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key
                  key: JWT_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: booki
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-srv
spec:
  selector:
    app: exchange
  ports:
  - name: exchange
    protocol: TCP
    port: 3004
    targetPort: 3004
