apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        # image: us.gcr.io/student-hub-381513/profile
        image: htekeste/profile
        env:
          - name: MONGO_URI
            value: "mongodb://profile-mongo-srv:27017/profile"
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret-key
                key: JWT_KEY
          - name: NATS_URL
            value: 'http://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: profile-srv
spec:
  selector:
    app: profile
  ports:
  - port: 4001
    targetPort: 4001
    name: profile-port
    protocol: TCP

