apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          # image: us.gcr.io/student-hub-381513/project
          image: htekeste/project
          env:
          - name: MONGO_URI
            value: "mongodb://project-mongo-srv:27017/project"
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret-key
                key: JWT_KEY
          - name: NATS_URL
            value: 'http://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: project-srv
spec:
  selector:
    app: project
  ports:
    - port: 4003
      targetPort: 4003
      name: project-port
      protocol: TCP
