apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-feed-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-feed
  template:
    metadata:
      labels:
        app: project-feed
    spec:
      containers:
        - name: project-feed
          image: htekeste/project-feed
          env:
          - name: MONGO_URI
            value: "mongodb://project-feed-mongo-srv:27017/ProjectFeed"
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret-key
                key: JWT_KEY
          - name: ELASTIC_CLOUD_ID
            valueFrom:
               secretKeyRef:
                 name: elastic-key
                 key: ELASTIC_CLOUD_ID
          - name: ELASTIC_USERNAME
            valueFrom:
               secretKeyRef:
                 name: elastic-username
                 key: ELASTIC_USERNAME
          - name: ELASTIC_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: elastic-password
                 key: ELASTIC_PASSWORD
          - name: NATS_URL
            value: 'http://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: project-feed-srv
spec:
  selector:
    app: project-feed
  ports:
    - port: 4004
      targetPort: 4004
      name: project-feed-port
      protocol: TCP
