apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - name: query
        image: us.gcr.io/student-hub-381513/query
        env:
            - name: MONGO_URI
              value: "mongodb+srv://meksonbravo903:meksonbravo903@cluster0.qgreox3.mongodb.net/?retryWrites=true&w=majority/query"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key
                  key: JWT_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: booki
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  ports:
  - name: query
    protocol: TCP
    port: 3003
    targetPort: 3003
