apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-post-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-post
  template:
    metadata:
      labels:
        app: question-post
    spec:
      containers:
      - name: question-post
        image: us.gcr.io/student-hub-381513/question-post
        # image: htekeste/question-post
        env:
          - name: MONGO_URI
            value: "mongodb+srv://meksonbravo903:meksonbravo903@cluster0.mre5bde.mongodb.net/QuestionPost?retryWrites=true&w=majority"
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret-key
                key: JWT_KEY
          - name: NLP_KEY
            valueFrom:
              secretKeyRef:
                name: nlp-api-key
                key: NLP_KEY
          - name: NATS_URL
            value: 'http://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: question-post-srv
spec:
  selector:
    app: question-post
  ports:
  - port: 4009
    targetPort: 4009
    name: question-post-port
    protocol: TCP
