apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-feed-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-feed
  template:
    metadata:
      labels:
        app: question-feed
    spec:
      containers:
        - name: question-feed
          image: htekeste/question-feed
          env:
            - name: MONGO_URI
              value: "mongodb://question-feed-mongo-srv:27017/QuestionFeed"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key
                  key: JWT_KEY
            - name: ELASTIC_CLOUD_ID
              valueFrom:
                secretKeyRef:
                  name: elastic-key
                  key: ELASTIC_CLOUD_ID
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-username
                  key: ELASTIC_USERNAME
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-password
                  key: ELASTIC_PASSWORD
            - name: NLP_KEY
              valueFrom:
                secretKeyRef:
                  name: nlp-api-key
                  key: NLP_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: question-feed-srv
spec:
  selector:
    app: question-feed
  ports:
    - port: 4010
      targetPort: 4010
      name: question-feed-port
      protocol: TCP
